//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PC_Component_Info.Lang {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PC_Component_Info.Lang.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drives ähnelt.
        /// </summary>
        public static string btnDrives {
            get {
                return ResourceManager.GetString("btnDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Efficiency Mode ähnelt.
        /// </summary>
        public static string btnEffMode {
            get {
                return ResourceManager.GetString("btnEffMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit ähnelt.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Feedback &amp; Support ähnelt.
        /// </summary>
        public static string btnFeedback {
            get {
                return ResourceManager.GetString("btnFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kill Task ähnelt.
        /// </summary>
        public static string btnKillTask {
            get {
                return ResourceManager.GetString("btnKillTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Task ähnelt.
        /// </summary>
        public static string btnNewTask {
            get {
                return ResourceManager.GetString("btnNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processors ähnelt.
        /// </summary>
        public static string btnProcessors {
            get {
                return ResourceManager.GetString("btnProcessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ram ähnelt.
        /// </summary>
        public static string btnRAM {
            get {
                return ResourceManager.GetString("btnRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Info ähnelt.
        /// </summary>
        public static string btnSysInfo {
            get {
                return ResourceManager.GetString("btnSysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tasks ähnelt.
        /// </summary>
        public static string btnTasks {
            get {
                return ResourceManager.GetString("btnTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your PC ähnelt.
        /// </summary>
        public static string btnYourPC {
            get {
                return ResourceManager.GetString("btnYourPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Fixed Performance Issues ähnelt.
        /// </summary>
        public static string clChangesFixes {
            get {
                return ResourceManager.GetString("clChangesFixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - Added Translation Support (currently en-en, de-de) ähnelt.
        /// </summary>
        public static string clNews {
            get {
                return ResourceManager.GetString("clNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Format ähnelt.
        /// </summary>
        public static string File_Format {
            get {
                return ResourceManager.GetString("File Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string tbAbout {
            get {
                return ResourceManager.GetString("tbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PC-Info is an official, licensed, modern and easy-to-use \nprogram from Adeptstack to find out what \ncomponents are installed in your PC. ähnelt.
        /// </summary>
        public static string tbAboutText {
            get {
                return ResourceManager.GetString("tbAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apps ähnelt.
        /// </summary>
        public static string tbApps {
            get {
                return ResourceManager.GetString("tbApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Architecture ähnelt.
        /// </summary>
        public static string tbArchitecture {
            get {
                return ResourceManager.GetString("tbArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background Tasks ähnelt.
        /// </summary>
        public static string tbBackgroundTasks {
            get {
                return ResourceManager.GetString("tbBackgroundTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base Clockspeed ähnelt.
        /// </summary>
        public static string tbBaseClockSpeed {
            get {
                return ResourceManager.GetString("tbBaseClockSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BIOS ähnelt.
        /// </summary>
        public static string tbBIOS {
            get {
                return ResourceManager.GetString("tbBIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Capacity ähnelt.
        /// </summary>
        public static string tbCapacity {
            get {
                return ResourceManager.GetString("tbCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string tbChangelog {
            get {
                return ResourceManager.GetString("tbChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cores ähnelt.
        /// </summary>
        public static string tbCores {
            get {
                return ResourceManager.GetString("tbCores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die CPU ähnelt.
        /// </summary>
        public static string tbCPU {
            get {
                return ResourceManager.GetString("tbCPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Driverversion ähnelt.
        /// </summary>
        public static string tbDriverVersion {
            get {
                return ResourceManager.GetString("tbDriverVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drives ähnelt.
        /// </summary>
        public static string tbDrives {
            get {
                return ResourceManager.GetString("tbDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Environment ähnelt.
        /// </summary>
        public static string tbEnvironment {
            get {
                return ResourceManager.GetString("tbEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fixes &amp; Changes ähnelt.
        /// </summary>
        public static string tbFixesChanges {
            get {
                return ResourceManager.GetString("tbFixesChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Memory ähnelt.
        /// </summary>
        public static string tbFreeMem {
            get {
                return ResourceManager.GetString("tbFreeMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Free Ram ähnelt.
        /// </summary>
        public static string tbFreeRam {
            get {
                return ResourceManager.GetString("tbFreeRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string tbGeneral {
            get {
                return ResourceManager.GetString("tbGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphicscard ähnelt.
        /// </summary>
        public static string tbGraphicscard {
            get {
                return ResourceManager.GetString("tbGraphicscard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icons ähnelt.
        /// </summary>
        public static string tbIcons {
            get {
                return ResourceManager.GetString("tbIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installed Ram ähnelt.
        /// </summary>
        public static string tbInstalledRam {
            get {
                return ResourceManager.GetString("tbInstalledRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This product is an open source project provided by Adeptstack. License: AGPL-3.0 license. © Adeptstack. All rights reserved ähnelt.
        /// </summary>
        public static string tbLicense {
            get {
                return ResourceManager.GetString("tbLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer ähnelt.
        /// </summary>
        public static string tbManufacturer {
            get {
                return ResourceManager.GetString("tbManufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maschinename ähnelt.
        /// </summary>
        public static string tbMaschineName {
            get {
                return ResourceManager.GetString("tbMaschineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string tbModel {
            get {
                return ResourceManager.GetString("tbModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modules ähnelt.
        /// </summary>
        public static string tbModules {
            get {
                return ResourceManager.GetString("tbModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Motherboard ähnelt.
        /// </summary>
        public static string tbMotherboard {
            get {
                return ResourceManager.GetString("tbMotherboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string tbName {
            get {
                return ResourceManager.GetString("tbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need help? ähnelt.
        /// </summary>
        public static string tbNeedHelp {
            get {
                return ResourceManager.GetString("tbNeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die News ähnelt.
        /// </summary>
        public static string tbNews {
            get {
                return ResourceManager.GetString("tbNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Filepath ähnelt.
        /// </summary>
        public static string tbOpenFilePath {
            get {
                return ResourceManager.GetString("tbOpenFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operatingsystem ähnelt.
        /// </summary>
        public static string tbOperatingsystem {
            get {
                return ResourceManager.GetString("tbOperatingsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string tbPrivacy {
            get {
                return ResourceManager.GetString("tbPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processes ähnelt.
        /// </summary>
        public static string tbProcesses {
            get {
                return ResourceManager.GetString("tbProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ram Used ähnelt.
        /// </summary>
        public static string tbRamInUse {
            get {
                return ResourceManager.GetString("tbRamInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reserved for Hardware ähnelt.
        /// </summary>
        public static string tbResForHW {
            get {
                return ResourceManager.GetString("tbResForHW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Threads ähnelt.
        /// </summary>
        public static string tbThreads {
            get {
                return ResourceManager.GetString("tbThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total Memory ähnelt.
        /// </summary>
        public static string tbTotalMem {
            get {
                return ResourceManager.GetString("tbTotalMem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Total usable Ram ähnelt.
        /// </summary>
        public static string tbTotalUseableRam {
            get {
                return ResourceManager.GetString("tbTotalUseableRam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferrate ähnelt.
        /// </summary>
        public static string tbTransferrate {
            get {
                return ResourceManager.GetString("tbTransferrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string tbType {
            get {
                return ResourceManager.GetString("tbType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string tbUpdate {
            get {
                return ResourceManager.GetString("tbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string tbUsername {
            get {
                return ResourceManager.GetString("tbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Utilization ähnelt.
        /// </summary>
        public static string tbUtilization {
            get {
                return ResourceManager.GetString("tbUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string tbVersion {
            get {
                return ResourceManager.GetString("tbVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Voltage ähnelt.
        /// </summary>
        public static string tbVoltage {
            get {
                return ResourceManager.GetString("tbVoltage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website ähnelt.
        /// </summary>
        public static string tbWebseite {
            get {
                return ResourceManager.GetString("tbWebseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What&apos;s new in this version ähnelt.
        /// </summary>
        public static string tbWNITV {
            get {
                return ResourceManager.GetString("tbWNITV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string tpClose {
            get {
                return ResourceManager.GetString("tpClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimize ähnelt.
        /// </summary>
        public static string tpMinimize {
            get {
                return ResourceManager.GetString("tpMinimize", resourceCulture);
            }
        }
    }
}
